apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "civicrm-drupal.fullname" . }}-civicrm-settings
  labels:
    {{- include "civicrm-drupal.labels" . | nindent 4 }}
data:
  settings.php: |
    <?php
    $databases['default']['default'] = [
      'database'        => '{{ .Values.app.drupalDb.name }}',
      'username'        => '{{ .Values.app.drupalDb.user }}',
      'password'        => getenv('DRUPAL_DB_PASSWORD'),
      'host'            => '{{ include "civicrm-drupal.dbHost" . }}',
      'port'            => '{{ .Values.app.drupalDb.port }}',
      'driver'          => 'mysql',
      'prefix'          => '',
      'isolation_level' => 'READ COMMITTED',
      'namespace'       => 'Drupal\\mysql\\Driver\\Database\\mysql',
      'autoload'        => 'core/modules/mysql/src/Driver/Database/mysql/',
    ];
    $settings['config_sync_directory'] = 'sites/default/files/config/sync';
    $settings['hash_salt'] = '{{ .Values.app.drupalDb.name }}-{{ include "civicrm-drupal.dbHost" . }}-civicrm-docker';
  civicrm.settings.php: |
    <?php
    global $civicrm_root, $civicrm_setting, $civicrm_paths;

    if (!defined('CIVICRM_UF')) {
      if (getenv('CIVICRM_UF')) {
        define('CIVICRM_UF', getenv('CIVICRM_UF'));
      } else {
        define('CIVICRM_UF', 'Drupal8');
      }
    }
    if (!defined('CIVICRM_UF_DSN') && CIVICRM_UF !== 'UnitTests') {
      define('CIVICRM_UF_DSN', 'mysql://{{ .Values.app.drupalDb.user }}:' . getenv('DRUPAL_DB_PASSWORD') . '@{{ include "civicrm-drupal.dbHost" . }}:{{ .Values.app.drupalDb.port }}/{{ .Values.app.drupalDb.name }}?new_link=true');
    }
    $civicrm_paths['civicrm.files']['url']  = '{{ .Values.app.drupal.baseUrl }}/sites/default/files/civicrm';
    $civicrm_paths['civicrm.files']['path'] = '/opt/drupal/web/sites/default/files/civicrm';
    $civicrm_paths['civicrm.private']['path'] = '/opt/drupal/web/sites/default/files/civicrm';
    if (!defined('CIVICRM_DSN')) {
      if (CIVICRM_UF === 'UnitTests') {
        if (isset($GLOBALS['_CV']['TEST_DB_DSN'])) {
          define('CIVICRM_DSN', $GLOBALS['_CV']['TEST_DB_DSN']);
        } else {
          throw new \Exception('$GLOBALS["_CV"]["TEST_DB_DSN"] is not set');
        }
      } else {
        define('CIVICRM_DSN', 'mysql://{{ include "civicrm-drupal.civicrmDbUser" . }}:' . getenv('CIVICRM_DB_PASSWORD') . '@{{ include "civicrm-drupal.civicrmDbHost" . }}:{{ .Values.app.civicrmDb.port }}/{{ .Values.app.civicrmDb.name }}?new_link=true');
      }
    }
    if (!defined('CIVICRM_LOGGING_DSN')) {
      define('CIVICRM_LOGGING_DSN', CIVICRM_DSN);
    }
    $civicrm_root = '/opt/drupal/vendor/civicrm/civicrm-core/';
    if (!defined('CIVICRM_TEMPLATE_COMPILEDIR')) {
      define('CIVICRM_TEMPLATE_COMPILEDIR', '/opt/drupal/web/sites/default/files/civicrm/templates_c');
    }
    if (!defined('CIVICRM_UF_BASEURL')) {
      define('CIVICRM_UF_BASEURL', '{{ .Values.app.drupal.baseUrl }}');
    }
    if (!defined('CIVICRM_DEDUPE_OPTIMIZER')) {
      define('CIVICRM_DEDUPE_OPTIMIZER', FALSE);
    }
    if (!defined('CIVICRM_SITE_KEY')) {
      define('CIVICRM_SITE_KEY', getenv('CIVICRM_SITE_KEY') ?: '');
    }
    if (!defined('CIVICRM_CRED_KEYS')) {
      define('CIVICRM_CRED_KEYS', getenv('CIVICRM_CRED_KEYS') ?: '');
    }
    if (!defined('CIVICRM_SIGN_KEYS')) {
      define('CIVICRM_SIGN_KEYS', getenv('CIVICRM_SIGN_KEYS') ?: '');
    }
    if (!defined('CIVICRM_MAIL_SMARTY')) {
      define('CIVICRM_MAIL_SMARTY', 0);
    }
    if (!defined('CIVICRM_DOMAIN_ID')) {
      define('CIVICRM_DOMAIN_ID', 1);
    }
    if (!defined('CIVICRM_DB_CACHE_CLASS')) {
      define('CIVICRM_DB_CACHE_CLASS', 'ArrayCache');
    }
    if (!defined('CIVICRM_DB_CACHE_HOST')) {
      define('CIVICRM_DB_CACHE_HOST', 'localhost');
    }
    if (!defined('CIVICRM_DB_CACHE_PORT')) {
      if (CIVICRM_DB_CACHE_CLASS === 'Redis') {
        define('CIVICRM_DB_CACHE_PORT', 6379);
      } else {
        define('CIVICRM_DB_CACHE_PORT', 11211);
      }
    }
    if (!defined('CIVICRM_DB_CACHE_PASSWORD')) {
      define('CIVICRM_DB_CACHE_PASSWORD', '');
    }
    if (!defined('CIVICRM_DB_CACHE_TIMEOUT')) {
      define('CIVICRM_DB_CACHE_TIMEOUT', 3600);
    }
    if (!defined('CIVICRM_DB_CACHE_PREFIX')) {
      define('CIVICRM_DB_CACHE_PREFIX', '');
    }
    if (!defined('CIVICRM_PSR16_STRICT')) {
      define('CIVICRM_PSR16_STRICT', FALSE);
    }
    define('CIVICRM_DEADLOCK_RETRIES', 3);
    if (CIVICRM_UF === 'UnitTests') {
      if (!defined('CIVICRM_CONTAINER_CACHE')) define('CIVICRM_CONTAINER_CACHE', 'auto');
    }
    if (strtoupper(substr(PHP_OS, 0, 3)) !== 'WIN' && !defined('CIVICRM_EXCLUDE_DIRS_PATTERN')) {
      define('CIVICRM_EXCLUDE_DIRS_PATTERN', '@/(\.|node_modules|js/|css/|bower_components|packages/|sites/default/files/private)@');
    }
    $include_path = '.'           . PATH_SEPARATOR .
                    $civicrm_root . PATH_SEPARATOR .
                    $civicrm_root . DIRECTORY_SEPARATOR . 'packages' . PATH_SEPARATOR .
                    get_include_path();
    if (set_include_path($include_path) === false) {
       echo "Could not set the include path<p>";
       exit();
    }
    if (!defined('CIVICRM_CLEANURL')) {
      if (function_exists('variable_get') && variable_get('clean_url', '0') != '0') {
        define('CIVICRM_CLEANURL', 1);
      } elseif (function_exists('config_get') && config_get('system.core', 'clean_url') != 0) {
        define('CIVICRM_CLEANURL', 1);
      } elseif (function_exists('get_option') && get_option('permalink_structure') != '') {
        define('CIVICRM_CLEANURL', 1);
      } else {
        define('CIVICRM_CLEANURL', 0);
      }
    }
    $memLimitString = trim(ini_get('memory_limit'));
    $memLimitUnit   = strtolower(substr($memLimitString, -1));
    $memLimit       = (int) $memLimitString;
    switch ($memLimitUnit) {
        case 'g': $memLimit *= 1024;
        case 'm': $memLimit *= 1024;
        case 'k': $memLimit *= 1024;
    }
    if ($memLimit >= 0 and $memLimit < 134217728) {
        ini_set('memory_limit', '128M');
    }
    require_once 'CRM/Core/ClassLoader.php';
    CRM_Core_ClassLoader::singleton()->register();
