{{- if .Values.persistence.sites.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "civicrm-drupal.fullname" . }}-sites
  labels:
    {{- include "civicrm-drupal.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.sites.accessMode }}
  {{- if .Values.persistence.sites.storageClass }}
  storageClassName: {{ .Values.persistence.sites.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.sites.size }}
{{- end }}
{{- if .Values.persistence.private.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "civicrm-drupal.fullname" . }}-private
  labels:
    {{- include "civicrm-drupal.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.private.accessMode }}
  {{- if .Values.persistence.private.storageClass }}
  storageClassName: {{ .Values.persistence.private.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.private.size }}
{{- end }}
