{{- if not .Values.app.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "civicrm-drupal.fullname" . }}-app
  labels:
    {{- include "civicrm-drupal.labels" . | nindent 4 }}
type: Opaque
stringData:
  drupal-admin-password: {{ .Values.app.drupal.admin.password | quote }}
  drupal-db-password: {{ .Values.app.drupalDb.password | quote }}
  civicrm-db-password: {{ .Values.app.civicrmDb.password | default .Values.app.drupalDb.password | quote }}
  civicrm-site-key: {{ .Values.app.civicrmSiteKey | quote }}
  civicrm-cred-keys: {{ .Values.app.civicrmCredKeys | quote }}
  civicrm-sign-keys: {{ .Values.app.civicrmSignKeys | quote }}
{{- end }}
