apiVersion: v2
name: civicrm-drupal
description: CiviCRM on Drupal — includes optional MariaDB, Ingress and persistent volumes
type: application
version: 0.1.0
appVersion: "6.10.1"
keywords:
  - civicrm
  - drupal
  - crm
sources:
  - https://github.com/josaur/civicrm-docker
maintainers:
  - name: josaur
    email: claude@josaur.de
dependencies:
  - name: mariadb
    version: "20.x.x"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: mariadb.enabled
